<a href="https://colab.research.google.com/github/tatadivine/Machine-Learning/blob/Master/linear_Regression_multiple_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv("homeprices (1).csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [12]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Let's go ahead and start training our model since we have cleaned the data and replaced missing values

In [13]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [14]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
reg.intercept_

np.float64(221323.00186540396)

In [18]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498408.25158031])

In [19]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([578876.03748933])