<a href="https://colab.research.google.com/github/tatadivine/Machine-Learning/blob/Master/NaiveBayes_titanic_survivers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [2]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [3]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [6]:
dummies = pd.get_dummies(inputs.Sex, dtype=int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

**I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female**

In [8]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [10]:
inputs.columns[inputs.isna().any()]

inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [12]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(7)

   Pclass        Age     Fare  female
0       3  22.000000   7.2500       0
1       1  38.000000  71.2833       1
2       3  26.000000   7.9250       1
3       1  35.000000  53.1000       1
4       3  35.000000   8.0500       0
5       3  29.699118   8.4583       0
6       1  54.000000  51.8625       0

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [15]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
model.score(X_test,y_test)

0.7723880597014925

In [18]:
X_test[0:10]

     Pclass        Age      Fare  female
301       3  29.699118   23.2500       0
1         1  38.000000   71.2833       1
856       1  45.000000  164.8667       1
658       2  23.000000   13.0000       0
703       3  25.000000    7.7417       0
122       2  32.500000   30.0708       0
457       1  29.699118   51.8625       1
493       1  71.000000   49.5042       0
117       2  29.000000   21.0000       0
666       2  25.000000   13.0000       0

In [19]:
y_test[0:10]

301    1
1      1
856    1
658    0
703    0
122    0
457    1
493    0
117    0
666    0
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[0:10])

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0])

In [21]:
model.predict_proba(X_test[:10])

array([[9.63848548e-01, 3.61514519e-02],
       [2.16686292e-02, 9.78331371e-01],
       [1.31072022e-06, 9.99998689e-01],
       [9.20959803e-01, 7.90401974e-02],
       [9.61558567e-01, 3.84414334e-02],
       [9.23183919e-01, 7.68160812e-02],
       [5.03465251e-02, 9.49653475e-01],
       [4.31843724e-01, 5.68156276e-01],
       [9.27536884e-01, 7.24631160e-02],
       [9.24162455e-01, 7.58375454e-02]])